version: '3.7'
services:
  bl-back:
    depends_on:
      - db
    build: .
    ports:
      - "9091:5000"
    environment:
      - PROFILES_OPTION=-Dspring-boot.run.profiles=production
  bl-front:
    depends_on:
      - bl-back
    build:
      context: ./front-dockerized/
      dockerfile: ./Dockerfile
    ports:
      - "8081:80"
    environment:
      - PROFILES_OPTION=-Dspring-boot.run.profiles=production
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: book-library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
#    volumes:
#      - d:\docker-mounts\postgres:/data/postgres
    ports:
      - 5433:5432
