== 22 Spring Security: Механизмы аутентификации

+++ <details><summary> +++
Изучаемый стек
+++ </summary><div> +++

- Spring Boot 2
- Spring data JPA
- Spring WEB
- VueJS
- Spring Security
- JUnit 5

- Libraries:

    lombok        code generator

+++ </div></details> +++

=== Техническое задание

- Docker, оркестрация, облака, облачные хостинги
- Обернуть приложение в docker-контейнер. Dockerfile принято располагать в корне репозитория. В image должна попадать JAR-приложения. Сборка в контейнере рекомендуется, но не обязательна.
- Если Вы не используете кастомные плагины для БД, не нужно делать для нее отдельный Dockerfile. Лучше взять готовый образ
- Настроить связь между контейнерами, с помощью docker-compose
- Опционально: сделать это в локальном миникубе.
- Приложение желательно реализовать с помощью всех Best Practices Docker (логгирование в stdout и т.д.)


=== Предустановки

- Yarn или NPM

=== Запуск

- cd %project-base-dir%/backend
- mvn spring-boot:run
- cd %project-base-dir%/frontend
- npm i OR yarn
- npm serve OR yarn serve

=== Развернутое приложение

- Пользовательский интерфейс
    http://localhost:8080/
- REST сервисы
    http://localhost:9090/

=== Авторизация

- a@a.a password
- u@u.u password
