app:
  ui-client-id: book-library-id
  ui-client-secret: secret
#  access-token-lifetime: 10
  access-token-lifetime: 7200
  refresh-token-lifetime: 21600
#  keystore-path: absolute path to keystore

spring:
  profiles.active: development
  jpa:
    show-sql: true
    database: default
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        batch_fetch_style: dynamic
        default_batch_fetch_size: 30
        jdbc:
          batch_size: 30
logging:
  level:
    root: info
    org.springframework: info

---
# docker port binding 8091
server.port: 5000
spring:
  profiles: production
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/book-library
    username: postgres
    password: postgres

---
server.port: 9090
spring:
  profiles: development
  datasource:
    initialization-mode: always
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:book-library
    # tcp connection jdbc:h2:tcp://localhost:7072/mem:book-library
    # web connection http://localhost:8082  jdbc:h2:mem:book-library
    username: sa
    password:
logging:
  level:
    root: info
    org.springframework: debug

---
